version: "3"

tasks:
  build:
    desc: Build the binary
    cmds:
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o drone-go-coverage

  docker-build:
    desc: Create docker image
    deps: [build]
    cmds:
      - docker build --platform=linux/amd64 -t alexwilkerson/drone-go-coverage .

  docker-tag:
    desc: Create docker image
    cmds:
      - docker tag alexwilkerson/drone-go-coverage:latest alexwilkerson/drone-go-coverage:latest

  docker-push:
    desc: Push docker image
    cmds:
      - docker push alexwilkerson/drone-go-coverage:latest

  publish:
    desc: Publish docker image
    cmds:
      - task: docker-build
      - task: docker-tag
      - task: docker-push
      - rm drone-go-coverage
